### ISSUE TITLE
Banner on individual trial pages with certificates of delay display incorrect information

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#104]
Per the [Clinicaltrials.gov Results](https://clinicaltrials.gov/ct2/show/results/NCT02413372) tab for this trial, it has received a certificate of delay for results.

This means results can be delayed for up to 2 additional years. This is hard coded into our `results_due` logic and has it's own flag in the data `has_certificate`.

Seems there is a big somewhere where when an individual trials has a certificate of delay, even though it would then still be considered "ongoing" in terms of its results status (we may want to think about terminology we use there?) and therefore not late on results, the banner still says it was due to report results 1 year from the Primary Completion Date.

[Here](https://fdaaa.trialstracker.net/trial/NCT02413372/)

![image](https://user-images.githubusercontent.com/25153969/37086461-8bd41800-21ef-11e8-831c-d630a1f681a4.png)

For trials that have certificates, perhaps we can put copy along the lines of:

"This trial is completed but has been granted a delay in reporting its results."

**Comment by sebbacon** [comment]
To be clear, that means the effective due date is the completion date plus three years?

**Comment by NickCEBM** [comment]
Yes. In practice it could be sooner but we have no way to distinguish that so we just assume the full time period.
