### ISSUE TITLE
Connect blogs from EBM Datalab website to FDAAA website

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#124]
Will add header button to "Blog" which will point to EBMDatalab.net blogs with FDAAA tag.

**Comment by NickCEBM** [comment]
Helen is updating the tags on the blogs Ben posts but eventually we will want to link this URL to the FDAAA website:

https://ebmdatalab.net/tag/fdaaa/

**Comment by sebbacon** [comment]
When is "eventually"?

**Comment by NickCEBM** [comment]
Whenever you have a moment to add a "Blog" button to the top of the wesbite! 

It's good to go now but also wasn't the highest priority if you had other more pressing things to take care of.
