### ISSUE TITLE
Automate Checking Diff in Trials for each Update

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#126]
I have been manually checking which "overdue" trials show up everyday and which ones drop off the "overdue" list.

This involves downloading that day's data and manually comparing it to my running list (basically the previous day's data).

As our list continues to grow and we're sure everything is running smoothly, it would be great if we could eventually automate this so a file is generated somewhere that simply has:

1. All the overdue trials added with that update
2. All the overdue trials that are no longer overdue for any reason

I can then record 1 and manually look into 2 for our records.

**Comment by sebbacon** [comment]
@NickCEBM, if you visit [the API](https://staging-fdaaa.ebmdatalab.net/api/) and go to "trials", and then click "Filters" button (top right), there are two new filters: *Is no longer overdue today*, and *Is overdue today*.

Selecting these filters will take you to something like [this page])https://staging-fdaaa.ebmdatalab.net/api/trials/?has_exemption=1&has_results=1&results_due=1&sponsor=&status=&is_pact=1&is_overdue_today=3&is_no_longer_overdue_today=2), which you could bookmark. You can download this as a CSV if you like, using the *GET* dropdown (also top right, also bookmarkable).
