### ISSUE TITLE
What displays on Google

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#143]
1. What shows up as the description text

2. What shows up as the headline which can be out of date when a trial moves from "Ongoing" to "Overdue"

![image 2](https://user-images.githubusercontent.com/25153969/39123623-48677ce4-46f0-11e8-93da-864e850bc4e1.png)

**Comment by sebbacon** [comment]
What is the desired behaviour?

**Comment by NickCEBM** [comment]
I think the idea was that both are archived at one point and time but as the status of the trial changes, we should try and have what appears on google show up. For instance this trial:

http://fdaaa.trialstracker.net/trial/NCT02027025/

Just went overdue but when searching it will by ongoing:

https://www.google.co.uk/search?q=NCT02027025&oq=NCT02027025&aqs=chrome..69i57j69i60l3.775j0j7&sourceid=chrome&ie=UTF-8

I believe the idea was we should try to expedite how that updates on Google if possible, especially in the wake of the amount of natural traffic we are getting from those apparently.

Might have to check with Ben if we want the description text to reflect anything else.

**Comment by NickCEBM** [comment]
Also might want to consider the behavior of trials that drop from the tracker for one reason or another (usually they lose their pact/ACT status) but they are still indexed and their individual trial page still shows up when you google it. Not sure if we care about that but we should probably be asking ourselves if we do.
