### ISSUE TITLE
New "Results Submitted" Format

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#146]
There is a new data element in the "Results Submitted" table that we regularly scrape until results are posted. This indicates when submitted information has been "Cancelled."

It appears that if some information is submitted then further changed by the sponsor prior to QC but the not resubmitted you get something like this:
https://clinicaltrials.gov/ct2/show/results/NCT02013674

![image](https://user-images.githubusercontent.com/25153969/40005157-2e0e46d4-578f-11e8-9bed-bd4158874a61.png)

It appears that if the information is then resubmitted, it looks like this:
https://clinicaltrials.gov/ct2/show/results/NCT02210858

![image](https://user-images.githubusercontent.com/25153969/40005215-4d1479f4-578f-11e8-9abc-9de1546d8c30.png)

Some of this information is now captured in the XML record as well (Per May 11 update [here](https://clinicaltrials.gov/ct2/about-site/new)) however it is not permanent as only the first and last date will be preserved in the record once the actual results are posted. In order to track the entire back and forth of the review process, we should continue our scraping, however we need to makes sure our scrape is not broken by the addition of the "Cancelled" field on some entries. Still, it may be worthwhile to discuss how to implement this in the best way for the tracker.

We also need to, in instances such as the first example above, make it so that a Cancelled submission without a re-submission also listed is no longer identified as having posted results on the tracker. 

For these examples, we don't know the exact day the results were cancelled so we have to discuss how we would like this to interact with fines. From 8 May on we will know the exact date the results were cancelled and can adjust our calculations accordingly.

**Comment by sebbacon** [comment]
Can you find any examples where the date is known? (As opposed to  "Canceled - Date Unknown")

**Comment by NickCEBM** [comment]
There isn't one in our sample yet but let me check the raw json as this should be something we could see in there.

**Comment by NickCEBM** [comment]
To deal with how these trials interact with the headline tracking numbers we have decided:

1. When a trial has cancelled results, they are "Overdue" for purposes of the overall headline stats until they submit new, not cancelled results.
2. We would like to create a new status for these trials. Somethings like "Overdue - Cancelled Results" or something like that which persists until new, not cancelled results are submitted.
3. Trials in this status should not accrue any new fines beyond any fines they accrued prior to submitting their first instance of results (if there were any).
