### ISSUE TITLE
Some "reported" trials are incorrectly displayed in "no longer overdue" filter

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#155]
The May 31st update led to some odd behaviour in the API.

Basically, three trials showed up when you filter by "is not longer overdue" in the API but they were never listed as overdue in the first place. The common thread is that all 3 would have come overdue today but had submitted results at some point in the last month. 2 of them are now "reported late" and 1 is "reported' which all seems correct. None of the three have any other recent updates to their data.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/25153969/40776924-224ae662-64c4-11e8-9810-8aa7ad1cd39c.png">

NCT00953576 had results submitted on May 21st
NCT01968213 on May 8th
NCT02176291 on April 26th

Just to show an example, here is NCT02176291 on the live site with May 30th data

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/25153969/40777415-b51c6b40-64c5-11e8-849c-bbd6c8149149.png">

And here it is on staging with May 31st data

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/25153969/40777440-c4cc1644-64c5-11e8-92a2-ace7f36c4330.png">

The other two are the same story only "Reported Late" instead of on-time in the May 31st data.

So a few things might be happening here:
1. There is a bug or some unanticipated behaviour somewhere in the "Results Submitted" scraping and how that interacts with trial status and when things become due. Things that were never "Overdue" have never showed up in this filter before that I can remember.
2. Everything on our end worked correctly but ClinicalTrials.gov randomly only just posted all 3 "Results Submitted" tabs for these trials today causing some confusion. I'm not entirely sure why, even if that is the case, they showed up in the "no longer overdue" filter as none of them were ever without results long enough to become "overdue" but perhaps that's just a weird interaction with the date since they would have come due today?

**Comment by NickCEBM** [comment]
Thinking about this, I have a hypothesis as to why this occurred.

I believe we don't scrape for QC status until something becomes overdue. So what I imagine happened here is that these trials were never checked prior to becoming due. Then they became "overdue" because that step happens first in the process, and then the QC check happened and they were immediately removed but because of the order of operations, the API recognised that as them going overdue and then leaving overdue status despite that never actually occurring on the website.

**Comment by sebbacon** [comment]
Not working today to check but that is 100% plausible

**Comment by sebbacon** [comment]
The question is, what do we want the behaviour to be? Although not strictly correct it is, possibly, kind of useful?

Otherwise, I can change the code so the default starting state is empty, rather than `overdue`.

**Comment by NickCEBM** [comment]
Well, not sure if its useful but it's also not a huge inconvenience. Just takes me a little more time to check and investigate when it happens. Now that we have a good idea as to why it happened and know the behaviour that it causing it is something benign, I'm less worried. Actually a little surprised it hadn't come up before.

**Comment by LydiaBerry** [comment]
Per today's update, two more trials appeared in the "Is No Long Overdue Today" API filter that reported late but in less than the 30-day window to become "overdue" by our standards. This means it wasn't just a function of it being the end-of-the-month defaulted trials. This is a new behavior that the API never did before.

![image](https://user-images.githubusercontent.com/38752825/40915762-418273e2-67cb-11e8-8f66-dac88d43a511.png)

**Comment by NickCEBM** [comment]
Once more, same story with NCT03086018

They have all fit the same story. I'm going to assume my hypothesis is correct here.

**Comment by NickCEBM** [comment]
https://clinicaltrials.gov/ct2/show/study/NCT02116959

This issue showed up again today with this trial. Changed from "N/A" to "Phase 1" so it dropped from being a pACT and then didn't show up on the API as dropped. I believe you said next time this happens to call it out and not deploy so I will do that!

**Comment by sebbacon** [comment]
Running investigation log:

* We only use the QA / Results Submitted data to determine the date something has been reported/submitted, for the purposes of defining how many days late it is.  
* A trial which is any number of days late is either marked `overdue` or `reported late`.  
* This only happens at the end of the daily import, not twice per @NickCEBM's hypothesis (i.e. not once when the tab is scraped and once a bit later)

**Comment by sebbacon** [comment]
Trial NCT02176291 has the following QA data on record:

* submitted to regulator: 2018/4/26; returned to sponsor: 2018/5/30
* submitted to regulator: 2018/5/31

NCT00953576 has this:

* submitted: 2018/04/26; returned 2018/05/30
* submitted: 2018/05/31

NCT03086018:

* submitted 2017/11/16

**Comment by sebbacon** [comment]
@NickCEBM we'll have to do another "pause updating live from staging" thing next time we see this, for more debugging.

**Comment by sebbacon** [comment]
New example. 

Yesterday (i.e. currently on live):
```
clinicaltrials=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02815293';
  id   | previous_status | status  | updated_date | start_date 
-------+-----------------+---------+--------------+------------
 38283 | ongoing         | ongoing | 2018-07-20   | 2016-09-30
(1 row)

clinicaltrials=> select * from frontend_trialqa where trial_id = 38283;
 id | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
----+------------------------+---------------------+----------+----------------------------+----------------------
(0 rows)
```

Today (i.e. currently on staging):
```
clinicaltrials_staging=> select previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02815293';

select * from frontend_trialqa where trial_id = 38283;
  previous_status  |  status  | updated_date | start_date 
-------------------+----------+--------------+------------
 overdue-cancelled | reported | 2018-07-23   | 2016-09-30

 id  | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
-----+------------------------+---------------------+----------+----------------------------+----------------------
 964 | 2018-06-18             |                     |    38283 | f                          | 2018-06-19
 965 | 2018-06-19             |                     |    38283 |                            | 
```

**Comment by sebbacon** [comment]
Yesterday:
```
clinicaltrials=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02825251';
  id   | previous_status | status  | updated_date | start_date 
-------+-----------------+---------+--------------+------------
 35391 | ongoing         | ongoing | 2018-07-20   | 2016-07-06

clinicaltrials=> select * from frontend_trialqa where trial_id = 35391;
 id | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
----+------------------------+---------------------+----------+----------------------------+----------------------
(0 rows)
```

Today:
```
clinicaltrials_staging=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02825251';
  id   | previous_status |    status     | updated_date | start_date 
-------+-----------------+---------------+--------------+------------
 35391 | overdue         | reported-late | 2018-07-23   | 2016-07-06

clinicaltrials_staging=> select * from frontend_trialqa where trial_id = 35391;
 id  | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
-----+------------------------+---------------------+----------+----------------------------+----------------------
 963 | 2018-06-27             |                     |    35391 |                            | 
(1 row)
```

**Comment by sebbacon** [comment]
Friday:
```
clinicaltrials=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02318602';
  id   | previous_status | status  | updated_date | start_date 
-------+-----------------+---------+--------------+------------
 47017 | ongoing         | ongoing | 2018-07-20   | 2016-01-31
(1 row)

clinicaltrials=> select * from frontend_trialqa where trial_id = 47017;
 id | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
----+------------------------+---------------------+----------+----------------------------+----------------------
(0 rows)
```

Monday:
```
clinicaltrials_staging=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT02318602';
  id   | previous_status |    status     | updated_date | start_date 
-------+-----------------+---------------+--------------+------------
 47017 | overdue         | reported-late | 2018-07-23   | 2016-01-31
(1 row)

clinicaltrials_staging=> select * from frontend_trialqa where trial_id = 47017;
 id  | submitted_to_regulator | returned_to_sponsor | trial_id | cancellation_date_inferred | cancelled_by_sponsor 
-----+------------------------+---------------------+----------+----------------------------+----------------------
 966 | 2018-06-26             |                     |    47017 |                            | 
(1 row)
```

**Comment by sebbacon** [comment]
In the last two examples, the problem is that we compute the trial status twice, via a save hook...

https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/a92f1a42a3015d221531a3bd1331389a0ee91401/clinicaltrials/frontend/models.py#L192

...first, when the data is imported...

https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/a92f1a42a3015d221531a3bd1331389a0ee91401/clinicaltrials/frontend/management/commands/process_data.py#L223

...and then again after scraping the QA tab:

https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/a92f1a42a3015d221531a3bd1331389a0ee91401/clinicaltrials/frontend/models.py#L220

**Comment by sebbacon** [comment]
Note that we have seen, in the wild, examples where a change in status *hasn't* immediately been altered by data from the QA tab on the same day. So we are still seeing this issue in some edge cases about which more data should be collected after the change-on-the-same-day fixes have been deployed.

**Comment by sebbacon** [comment]
A new example of the outstanding part of this

```
clinicaltrials_staging=> select id, previous_status, status, updated_date, start_date from frontend_trial where registry_id = 'NCT03146403';
  id   | previous_status |  status  | updated_date | start_date 
-------+-----------------+----------+--------------+------------
 46274 | overdue         | reported | 2019-01-22   | 2017-05-24
(1 row)
```

It looks like it has submitted results, came due today and was checked, and so switched right to reported 
 which should just happen, but for some reason the API picked it up

**Comment by NickCEBM** [comment]
I think this is not longer an issue, so closing. Haven't seen it happen in quite some time. Can reopen if it pops up again.
