### ISSUE TITLE
Permissions problem on log file

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#157]
Every so often we are unable to restart the server because the log file at /var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/clinicialtrials.log is owned by root and not writable by `www-user` (which the Django app is running as).

Find out what's changing ownership and ensure always owned by `www-user`

**Comment by sebbacon** [comment]
Clues:

* The non-staging version hasn't been written to for ages (since April 30): `/var/www/fdaaa/clinicaltrials-act-tracker/clinicaltrials/frontend/clinicialtrials.log`
* The staging version was last written to at 09:58 when the `load_data` command finished

This appears to be related to how we kick off commands from ebmbot. Presumably sudo-related.

**Comment by chadmiller** [comment]
It's probably worthwhile to un-sudo-ify everything except a two-command
preparation step. The rest should be able to run as a mundane user.

Tiny sudo permissions for the installation/deployment account would be
nice. Can only sudo "mkdir", and "createdb", eg.

**Comment by sebbacon** [comment]
So here's what happens:

* The bot-initiated update runs via `sudo` (the account *does* only have access whitelisted commands, at least), meaning `manage.py` is ultimately running as root user
* The django logfile handler is set up to rotate log files at 15Mb
* The staging environment is logging at `DEBUG` level, so this happens several times in one update
* When the file is rotated, the new file is now owned by `root`
* The `www-data` user no longer has write access to the file

Fixes:

* I see no reason why the update command should run as root; fix that
* Increase the maximum size of the the log file - 15Mb is unecessarily small
* Reduce the log level

**Comment by sebbacon** [comment]
I opted to keep running the command via `sudo` so that our bot user `ebmbot` could itself set the user to `www-data`. The alternative was to change the log file to be group writable (which would require a custom `LogFileHandler`) and ensure `www-data` and `ebmbot` are in the same group, which (given our our devops currently doesn't include permissioning) would be more brittle and less discoverable in the medium term.

**Comment by madwort** [comment]
hoping to defer the issue with this https://github.com/ebmdatalab/clinicaltrials-act-tracker/commit/8e00f314af6438cc672949ea9d456a98717b59b7 - if it works, this may break again in ~2027, otherwise perhaps ~2023?
