### ISSUE TITLE
CSV generation failing due to excessive column width

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#179]
One of our absurdly-long columns has become too wide for BigQuery:

```
Error in FDAAA import: Traceback (most recent call last):
 File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/management/commands/load_data.py", line 212, in handle
   convert_and_download()
 File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/management/commands/load_data.py", line 159, in convert_and_download
   wait_for_job(job)
 File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/bigquery.py", line 336, in wait_for_job
   raise JobError(job.errors)
bigquery.JobError: [{'reason': 'invalid', 'location': 'gs://ebmdatalab/clinicaltrials/raw_clincialtrials_json_2019-02-14.csv', 'message': 'Error while reading table: ebmdatalab.clinicaltrials.current_raw_json, error message: Error detected while parsing row starting at position: 3732196783. Error: Field larger than the maximum allowed size.'}]
```

I recall this being an issue earlier with the "Study Results" page, which can include various metadata classifications that can be arbitrarily long and are stored as an array.

I don't recall what we did about this, and nor can I find an issue about it.

**Comment by sebbacon** [comment]
On reflection, the column-width problem I'm thinking of was in postgres. But no doubt the issue is the same.

For the record, I investigated postgres like this:

1. Find widest rows with `select eudract_number_with_country, octet_length(t.*::text) AS l FROM euctr AS t order by l desc limit 50;`
2. Find widest columns with `select avg(pg_column_size(imps)) from euctr;`

**Comment by sebbacon** [comment]
Yesterday's longest line is 2.1Mb in length! [Here it is, in its full glory](https://gist.github.com/sebbacon/f56945df0ecde0dc72fee4d57e6d940e). The massive field is `clinical_results`, which accounts for 1.9Mb.

I worked this out by counting all the line lengths:

    $ awk '{n+=1; print length() " " n}' raw_clincialtrials_json_2019-02-14.csv | sort -k1 -g | tail
    1021382 8419
    1046549 82735
    1068192 96352
    1099762 11835
    1126784 193677
    1165255 62523
    1245563 42184
    1271382 15985
    1354402 153801
    2197357 224517

(Note the longest line is much longer than the next-longest)

Then extracting them by line number:

    sed '224517!d'  raw_clincialtrials_json_2019-02-14.csv > long.json

I can reproduce original error  by running this in BigQuery:

    SELECT count(*) FROM ebmdatalab.clinicaltrials.current_raw_json

We can assume it's that field which is causing the problems.  We do query that to see if there are any results, so it's required by the current implementation of our transform pipeline.

**Comment by sebbacon** [comment]
Short-term fix would probably be to truncate the `clinical_results` field, perhaps here:

https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/d07b4eebc64e8b1bf7e8d6ca06fbb9524cd14c70/clinicaltrials/frontend/management/commands/load_data.py#L37-L42

Whatever the short-term fix, I think now that you're  starting to write python code @NickCEBM, it would be a hugely  worthwhile exercise for you to rewrite the SQL as python which works directly on the XML files.  This will remove a lot of complexity from the loading pipeline, making it easier to read and test.

**Comment by NickCEBM** [comment]
This PR removes out dependence on `clinical_results`. Don't need it anymore:

https://github.com/ebmdatalab/clinicaltrials-act-tracker/pull/180

Happy to redo in Python. A worthwhile project. Just give me what I need and tell me what to do to make it work with everything else.
