### ISSUE TITLE
Replace SQL transformation pipeline with Python

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#181]
These are notes for @NickCEBM to get started.

Initially, write some python that goes over all the example XML in [this zip file](https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/master/clinicaltrials/frontend/tests/fixtures/data.zip), and creates a CSV whose output matches [this file](https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/master/clinicaltrials/frontend/tests/fixtures/expected_trials_data.csv).

Initially, unzip the zip yourself, and have the code iterate over its contents using code based on this:

https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/d07b4eebc64e8b1bf7e8d6ca06fbb9524cd14c70/clinicaltrials/frontend/management/commands/load_data.py#L98-L124

When you've done this, we can have a session where I can explain how we can integrate this into the existing code base, including how to alter the automated tests.

**Comment by NickCEBM** [comment]
This has happened. Closing.
