### ISSUE TITLE
Trial Listed as Reported Late when it has it has no results

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#186]
This trial:

https://fdaaa.trialstracker.net/trial/NCT02106975/

Is listed on the Tracker as "Reported Late" but has no results, submitted or otherwise, on ClinicalTrials.gov. I tracked down the issue and it appears that it did have submitted results in QC but they, with today's update, mysteriously vanished.

I assume because we are comparing this to the old scraped data of the QC status, the tracker still thinks it has something submitted. 

Edit: Quick note for future reference. This trial was 25 days overdue in its submission before it got rid of its submitted results and got a Certificate of Delay so not in our "Overdue" records.

**Comment by sebbacon** [comment]
So to be completely clear: if QC vanishes, we should treat this as no results?

**Comment by NickCEBM** [comment]
Yes. Unless they show up again! According to what anyone looking at the trial entry today would see, they never submitted anything.

Looks like this specific trial went and got a certificate of delay so once we fix this it should become "Ongoing"

**Comment by NickCEBM** [comment]
Actually looks like the certificate of delay took care of making it "Ongoing" again, but this is good to fix anyway.

One note, we can, potentially, start to move away from the QC scraping and use the "pending results" section of the XML.
