### ISSUE TITLE
Scrollover Text

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#58]
Draft scrollover test for various site elements is here.

https://docs.google.com/document/d/1VNpSA02QJha7PUO82l4MVoj1k3-jeZ6qGofvhoEGgtc/edit?usp=sharing

These still need to be reviewed. Will respond to this comment when they are final.

**Comment by sebbacon** [comment]
I am not at all sure these are necessary - would appreciate a debate about this at next DL day!
