### ISSUE TITLE
Coloured box text too big to fit in boxes

### ISSUE THREAD

**Issue by alexwalkercebm** [ebmdatalab/clinicaltrials-act-tracker#59]
Using Chrome on Windows 7, this is the case for the ranked sponsors page:

![image](https://user-images.githubusercontent.com/24895935/36251518-6667dc66-1239-11e8-89a8-1a286e8c6cad.png)

....but looks fine on the all trials page:

![image](https://user-images.githubusercontent.com/24895935/36251648-cc457f3e-1239-11e8-9c80-2b3ee238c3ba.png)

**Comment by NickCEBM** [comment]
Still having this issue, even after a hard refresh on Chrome in Windows 7

![image](https://user-images.githubusercontent.com/25153969/36371654-ae58b152-155a-11e8-8407-410b18964887.png)

**Comment by sebbacon** [comment]
This is really hard to reproduce consistently.

Where I've been able to reproduce, the font size has been too large at 68.8px, when it should have been 58.3px.

**Comment by NickCEBM** [comment]
After a few hard refreshes, it looks like it's correct now.

**Comment by sebbacon** [comment]
That's the problem, it seems to go wrong randomly.

**Comment by NickCEBM** [comment]
I'm getting a very odd behaviour now in which, when it occurs, I hard refresh, then the text in the boxes gets bigger and bigger until it eventually settles on the correct size.

Not 100% reproducible so don't have a screen shot at the moment but it's happened twice.

**Comment by sebbacon** [comment]
You mean each time you refresh it gets bigger, until it doesn't?

**Comment by NickCEBM** [comment]
Yes, although I can't reproduce that since. Now if it is mis-sized it just goes to the right view after 1 refresh.

**Comment by sebbacon** [comment]
How often is it mis-sized?!

**Comment by NickCEBM** [comment]
Seems to happen most repeatably when I click from the "All Trials" view to the "Mixed Sponsor" view
