### ISSUE TITLE
SQL Review: whitelist or blacklist phases?

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#66]
In the specification, `phase` is "Not Phase 1", but we have implemented it as a whitelist of things that are not phase 1.

The current full list of phases is:
```
N/A
Early Phase 1
Phase 1 
Phase 1/Phase 2   
Phase 2 
Phase 2/Phase 3
Phase 3 
Phase 4 
```

It's conceivable `Phase 3/Phase 4` could appear in the list. Might it be safer to express this as 
```sql
phase NOT LIKE '%Phase 1'

```

(rather than the current:)

```sql
(phase = 'Phase 1/Phase 2' OR phase = 'Phase 2' OR Phase = 'Phase 2/Phase 3' or phase = 'Phase 3' or phase = 'Phase 4' or phase = 'N/A') 
  
```

**Comment by NickCEBM** [comment]
Yea, once again, this was Ben recommending doing it this way as a best practice. If you think differently we can change it in the actual code.

**Comment by sebbacon** [comment]
It depends on the desired failure mode. With a whitelist the risk is underspecification of ACTs and a blacklist it's overspecification.

Normally I'd say we want the former - but on the other hand, the latter is actually what is in the specification.

Probably the best thing to do is write a SQL query that checks expected values and returns rows if there are values not expected. I can then run this as a preflight check in the automated import procedure.

i.e. 

```sql
SELECT * FROM foo WHERE phase not in ['N/A', 'Early Phase 1', ...etc...]
```

Makes sense? If so please make a new issue "preflight SQL checks", close this one, and have a think about other code lists we might want to check (I can only think of `intervetion_types` off the top of my head but the consequences of getting that wrong are less clear).
