### ISSUE TITLE
SQL Review: pACT flag doesn't include `primary_purpose`

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#69]
![image](https://user-images.githubusercontent.com/211271/36369881-d623e4f0-1554-11e8-995c-9696fae9ae9a.png)

**Comment by NickCEBM** [comment]
This is correct. Making this change throughout.

**Comment by NickCEBM** [comment]
This is updated for the `website_data` table on BigQuery as well as the final query in issue #2 and in the paper.
