### ISSUE TITLE
Importer breaks when things are no longer ACTs

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#73]
Because the importer only does stuff with things flagged as (p)ACTs, if something goes from being flagged as such to not being flagged as such, none of its data gets updated.

In fact, all trials no longer in the list of ACTs should be deleted (or similar) from the database.

**Comment by sebbacon** [comment]
Hm. The concept of "zombie" trials should already address this.

@NickCEBM - can you supply a concrete example of where we think this happened?

**Comment by NickCEBM** [comment]
I don't know if something that lost ACT/pACT status yet. I only know of any example of something that went from due to not due.

**Comment by NickCEBM** [comment]
I not recall why this came up. It was that Bayer trial we removed when we altered the criteria. Based on an email we just got, this will likely happen again. Here is the record for the trial that switched from pACT to not a pACT at launch:

https://clinicaltrials.gov/show/NCT03012347

**Comment by sebbacon** [comment]
What's the email?

**Comment by sebbacon** [comment]
So to clarify: another Bayer trial is likely to have a field changed in CT.gov which will cause us to classify it as neither pACT nor ACT.

When this happens, the trial should disappear from the database.
