### ISSUE TITLE
Days Overdue Sort

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#74]
When sorting "Days Overdue" be descending, the top hit is currently a 0. There are not other 0s as this field is usually null if it wasn't late at all.

![image](https://user-images.githubusercontent.com/25153969/36382767-ffbd31c2-1581-11e8-9803-d82120e83fec.png)

**Comment by sebbacon** [comment]
`0` currently appears on overdue trials that are within the grace period.

Fix is always to use nulls for non-positive values
