### ISSUE TITLE
Preflight SQL checks

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#75]
Referencing issue #66 

We should check for unexpected values in the "Intervention Type" and "Phase" fields.

Will discuss how to implement and if any other fields need this.

**Comment by sebbacon** [comment]
@NickCEBM can you have a think about if this might be possible for any other fields? Then I can implement. Not sure it needs a discussion?

**Comment by NickCEBM** [comment]
Intervention Type is the big one and that can list multiple things. Right now I'm just looking for the terms in a reg_exp but here is an example:

"intervention": [{"intervention_type": "Procedure", "intervention_name": "adductor canal block", "description": "Continuous adductor canal block and single shot posterior tibial nerve block under ultrasound guidance and using nerve stimulating needle (bolus: 0.5% Ropivacaine 10-15ml with dexamethasone 4mg ;with single shot posterior tibial nerve block (8-10ml 0.5% ropivacaine)", "arm_group_label": "adductor canal block"}, {"intervention_type": "Procedure", "intervention_name": "femoral nerve block", "description": "Femoral nerve catheter inserted under ultrasound guidance using nerve stimulating needle administering ropivacaine bolus 10-15ml and infusing 0.2% ropivacaine at 4-6ml/h; plus a single shot posterior tibial nerve block under ultrasound guidance and use of nerve stimulating needle", "arm_group_label": "continuous femoral nerve block"}],

Obviously this is 2 instances of a "Procedure" so it can be different. Knowing all the things that appear as "intervention_type" and checking them against the criteria would be a good practice.

Phase is good to do just in case something new pops up but right now we have everything that exists covered.

Don't think it is necessary for Location which is the only other one I would think about using it for.

**Comment by NickCEBM** [comment]
This is probably a best practice but failing some major changes to the way ct.gov handles their data, probably not totally necessary. Closing for now.
