### ISSUE TITLE
Updating Fine Amounts

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#77]
It appears we can increase the amount of "fines" we are assessing in two ways.

First, [per this](https://www.law.cornell.edu/cfr/text/45/102.3), fines are adjusted for inflation over time. The Fine for 2017 for not reporting has actually increased to $11,569. Does not look like fines have been adjusted again for 2018 yet.
![image](https://user-images.githubusercontent.com/25153969/36417810-d24dbf7e-1624-11e8-88c5-34cd409f7835.png)

Secondly, per 333(f)(3)(A), and a re-reading of the final rule, I think once someone is late at all we can apply a one time fine of $11,569.

**Final Rule:**
>(a) Civil or criminal judicial actions. Failure to comply with the requirements of this part, issued under >section 402(j) of the Public Health Service Act (42 U.S.C. 282(j)), is a prohibited act under one or more >provisions of section 301(jj) of the Federal Food, Drug, and Cosmetic Act (21 U.S.C. 331(jj)):
...
>(2) Failure to submit clinical trial information required under section 402(j) of the Public Health Service >Act is a prohibited act under section 301(jj)(2) of the Federal Food, Drug, and Cosmetic Act.

**Comments from NIH on Final Rule;**
>New section 11.66(b) describes generally that any person who violates section 301(jj) of the FD&C Act is subject to civil monetary penalties under section 303(f)(3) of the FD&C Act (21 U.S.C. 333(f)(3)). Under FDAAA Title VIII’s addition of 303(f)(3) to the FD&C Act, a person who commits any of the prohibited acts described in section 301(jj)(1),(2), or (3) would be subject to a civil monetary penalty of ‘‘not more than $10,000 for all violations adjudicated in a single proceeding’’ (21 U.S.C. 333(f)(3)(A)). Under 402(j)(5)(C)(ii), if the Secretary determines that any clinical trial information was not submitted as required, or was false or misleading, the Secretary shall notify the responsible party and give them an opportunity to remedy the non-compliance within 30 days. As part of the civil monetary penalties provision, if the violation is not corrected within 30 days following such notification, the person is subject to an additional civil monetary penalty of ‘‘not more than $10,000 for each day of the violation’’ until the violation is corrected (21 U.S.C. 333(f)(3)(B)). 

Originally, I read this as the first part, regarding the violation of 301(jj) as just setting the legal precedent for the later $10,000 fine. However, looking a bit closer, I think non-compilers can be fined once at initially being late and then if they don't fix within 30 days, they can be fined more. This makes sense when you look at the 333(f)(3) referenced in the Final Rule:

**For Reference: [331(jj)](https://www.law.cornell.edu/uscode/text/21/331#jj)**
>The following acts and the causing thereof are prohibited:
...
>(jj)
>(1) The failure to submit the certification required by section 282(j)(5)(B) of title 42, or knowingly submitting a false certification under such section.
>(2) The failure to submit clinical trial information required under subsection (j) of section 282 of title 42.
>(3) The submission of clinical trial information under subsection (j) of section 282 of title 42 that is false or misleading in any particular under paragraph (5)(D) of such subsection (j).

**[333(f)(3):](https://www.law.cornell.edu/uscode/text/21/333#f)**
>(3)
>(A) Any person who violates section 331(jj) of this title shall be subject to a civil monetary penalty of not more than $10,000 for all violations adjudicated in a single proceeding.
>(B) If a violation of section 331(jj) of this title is not corrected within the 30-day period following notification under section 282(j)(5)(C)(ii) [2] of title 42, the person shall, **in addition to any penalty under subparagraph (A),** be subject to a civil monetary penalty of not more than $10,000 for each day of the violation after such period until the violation is corrected.

I've found a few other resources that now corroborate this view:

https://hso.research.uiowa.edu/clinicaltrialsgov

https://www.fda.gov/downloads/ForPatients/About/UCM410146.doc (Old but from the FDA, they mention the initial fine as well as the subsequent fine)

http://med.dartmouth-hitchcock.org/clinical_trials/what-are-the-penalties-for-failing-to-register.html

**Comment by sebbacon** [comment]
Feeback from a lawyer:

> You are right about the inflation amounts. I hadn’t realized that, but after reviewing what you sent and the statute again, yes, the penalties FDA can levy are now more than $10K.
>
> Do you mean Day 30 following notification of noncompliance? It’s important to recognize that the notification may not come immediately on the date of noncompliance, right, so the grace period can actually be longer than 30 days.
>
> I think this is challenging because I read 21 USC 333(f)(3)(A) the same way you do: $10K for violations, period. This seems to be independent of any notification or any grace period – the day you miss the deadline, you’re on for $10K.
> But there are two caveats that make me a little less certain:
>>  i.      It’s hard to calculate the initial $10K fine because it refers to all violations adjudicated in a single proceeding. So if a sponsor had 5 trials past the deadline, and they are all adjudicated together, how would you account for that in your tracker – since that would result in only 1 $10K fine, not 5?
>>
>>  ii.      I’m also wondering whether it is a fair exercise of enforcement discretion not to levy the initial $10K fine, and just wait till after the notice of noncompliance. Again, the statutory language seems to allow it right on the missed date – you’re right about that. However, if you look at (j)(5)(C)(ii), the fact that it talks about giving the party an opportunity to remedy noncompliance suggests that maybe it would be appropriate to not issue any fine till that opportunity has passed. On the other hand, that provision could also be fairly read to mean that you get your initial penalty of $10K on the date of noncompliance, and the govt waits to ding you further till you’ve failed to remedy after notice. 
>
> The bottom line is that if you want to take a conservative approach for your tracker, you could avoid inclusion of that initial $10K fine – but if you want to be a stickler for the letter of the law as written (which is also appropriate!), then you would include that initial $10K fine, subject to the problem mentioned above about violations adjudicated together.

**Comment by sebbacon** [comment]
@NickCEBM shall we close this now?

**Comment by NickCEBM** [comment]
Lets leave it open for the moment. I want to have a quick discussion with Ben on the initial fines.

**Comment by NickCEBM** [comment]
We have made a final decision not to implement the initial fine. Only the ones after 30 days.
