### ISSUE TITLE
Add link to twitter account

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#88]
Handle: `@FDAAAtracker`
* Link to twitter in header and footer
* Make the account tweet on each update ("2 trials became overdue today; fines due to US Govt now at $xxx")
*  Add [card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) to header and [validate](https://cards-dev.twitter.com/validator)

**Comment by sebbacon** [comment]
I think we should report on both overdue and late-reporting trials.  The problem is the wording.  The simplest is:

> Today, we found 3 due trials and 1 late-reporting trial

However, it doesn't cover that they are newly-due.  This does:

> Today, 3 additional trials went overdue, and 1 additional trial was reported late

But if we miss a day, then it's no longer accurate.  This is the most accurate:

> Today, we found 3 newly-overdue trials, and 1 newly-reported but late trial

But it sounds awkward.

Ideas?

**Comment by NickCEBM** [comment]
How about:

>Since our last update, 3 trials became overdue and 1 trial reported late. 5 trials reported their results on time.
